import Layout from "@/components/layout";
import "@/styles/globals.css";
import Providers from "@/utils/Providers";
import { LoadScript } from "@react-google-maps/api";
import { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { unstable_setRequestLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "ParkingLot-Manager",
  description: "Generated by crashsaverapp",
  icons: {
    icon: [
      {
        // media: '(prefers-color-scheme: dark)',
        url: "/images/favicon.ico",
        href: "/images/favicon.ico",
      },
    ],
  },
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  unstable_setRequestLocale(locale);
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body
        className={`flex flex-col h-screen w-full bg-light dark:bg-dark dark`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers params={{ locale }}>
            <Layout>{children}</Layout>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
