FROM golang:alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download

RUN go build -o bin/api cmd/api/main.go

FROM alpine:latest

WORKDIR /app

COPY env.development .

RUN mv env.development .env

COPY --from=builder /app/bin/api .

CMD ["./api"]
