version: "3.8"

services:
  assistance:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assistance
    ports:
      - "8000:8000"
    networks:
      - network

networks:
  network:
    external: true
