// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FCMService_SendMessageFCM_FullMethodName = "/fcm.FCMService/SendMessageFCM"
)

// FCMServiceClient is the client API for FCMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FCMServiceClient interface {
	SendMessageFCM(ctx context.Context, in *SendMessageFCMRequest, opts ...grpc.CallOption) (*SendMessageFCMResponse, error)
}

type fCMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFCMServiceClient(cc grpc.ClientConnInterface) FCMServiceClient {
	return &fCMServiceClient{cc}
}

func (c *fCMServiceClient) SendMessageFCM(ctx context.Context, in *SendMessageFCMRequest, opts ...grpc.CallOption) (*SendMessageFCMResponse, error) {
	out := new(SendMessageFCMResponse)
	err := c.cc.Invoke(ctx, FCMService_SendMessageFCM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FCMServiceServer is the server API for FCMService service.
// All implementations must embed UnimplementedFCMServiceServer
// for forward compatibility
type FCMServiceServer interface {
	SendMessageFCM(context.Context, *SendMessageFCMRequest) (*SendMessageFCMResponse, error)
	mustEmbedUnimplementedFCMServiceServer()
}

// UnimplementedFCMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFCMServiceServer struct {
}

func (UnimplementedFCMServiceServer) SendMessageFCM(context.Context, *SendMessageFCMRequest) (*SendMessageFCMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageFCM not implemented")
}
func (UnimplementedFCMServiceServer) mustEmbedUnimplementedFCMServiceServer() {}

// UnsafeFCMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FCMServiceServer will
// result in compilation errors.
type UnsafeFCMServiceServer interface {
	mustEmbedUnimplementedFCMServiceServer()
}

func RegisterFCMServiceServer(s grpc.ServiceRegistrar, srv FCMServiceServer) {
	s.RegisterService(&FCMService_ServiceDesc, srv)
}

func _FCMService_SendMessageFCM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageFCMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FCMServiceServer).SendMessageFCM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FCMService_SendMessageFCM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FCMServiceServer).SendMessageFCM(ctx, req.(*SendMessageFCMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FCMService_ServiceDesc is the grpc.ServiceDesc for FCMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FCMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fcm.FCMService",
	HandlerType: (*FCMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessageFCM",
			Handler:    _FCMService_SendMessageFCM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
