// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageFCM struct {
	FcmToken             string   `protobuf:"bytes,1,opt,name=fcmToken,proto3" json:"fcmToken,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Sound                string   `protobuf:"bytes,4,opt,name=sound,proto3" json:"sound,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageFCM) Reset()         { *m = MessageFCM{} }
func (m *MessageFCM) String() string { return proto.CompactTextString(m) }
func (*MessageFCM) ProtoMessage()    {}
func (*MessageFCM) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *MessageFCM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageFCM.Unmarshal(m, b)
}
func (m *MessageFCM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageFCM.Marshal(b, m, deterministic)
}
func (m *MessageFCM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageFCM.Merge(m, src)
}
func (m *MessageFCM) XXX_Size() int {
	return xxx_messageInfo_MessageFCM.Size(m)
}
func (m *MessageFCM) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageFCM.DiscardUnknown(m)
}

var xxx_messageInfo_MessageFCM proto.InternalMessageInfo

func (m *MessageFCM) GetFcmToken() string {
	if m != nil {
		return m.FcmToken
	}
	return ""
}

func (m *MessageFCM) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MessageFCM) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MessageFCM) GetSound() string {
	if m != nil {
		return m.Sound
	}
	return ""
}

type SendMessageFCMRequest struct {
	Fcm                  *MessageFCM `protobuf:"bytes,1,opt,name=fcm,proto3" json:"fcm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendMessageFCMRequest) Reset()         { *m = SendMessageFCMRequest{} }
func (m *SendMessageFCMRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageFCMRequest) ProtoMessage()    {}
func (*SendMessageFCMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *SendMessageFCMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageFCMRequest.Unmarshal(m, b)
}
func (m *SendMessageFCMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageFCMRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageFCMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageFCMRequest.Merge(m, src)
}
func (m *SendMessageFCMRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageFCMRequest.Size(m)
}
func (m *SendMessageFCMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageFCMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageFCMRequest proto.InternalMessageInfo

func (m *SendMessageFCMRequest) GetFcm() *MessageFCM {
	if m != nil {
		return m.Fcm
	}
	return nil
}

type SendMessageFCMResponse struct {
	Fcm                  *MessageFCM `protobuf:"bytes,1,opt,name=fcm,proto3" json:"fcm,omitempty"`
	Ok                   bool        `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendMessageFCMResponse) Reset()         { *m = SendMessageFCMResponse{} }
func (m *SendMessageFCMResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageFCMResponse) ProtoMessage()    {}
func (*SendMessageFCMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *SendMessageFCMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageFCMResponse.Unmarshal(m, b)
}
func (m *SendMessageFCMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageFCMResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageFCMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageFCMResponse.Merge(m, src)
}
func (m *SendMessageFCMResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageFCMResponse.Size(m)
}
func (m *SendMessageFCMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageFCMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageFCMResponse proto.InternalMessageInfo

func (m *SendMessageFCMResponse) GetFcm() *MessageFCM {
	if m != nil {
		return m.Fcm
	}
	return nil
}

func (m *SendMessageFCMResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*MessageFCM)(nil), "fcm.MessageFCM")
	proto.RegisterType((*SendMessageFCMRequest)(nil), "fcm.SendMessageFCMRequest")
	proto.RegisterType((*SendMessageFCMResponse)(nil), "fcm.SendMessageFCMResponse")
}

func init() {
	proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba)
}

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcb, 0x4b, 0x03, 0x31,
	0x10, 0x87, 0xe9, 0xd6, 0x47, 0x1d, 0xa1, 0xc2, 0x58, 0x4b, 0x58, 0x2f, 0xda, 0x93, 0xa7, 0x5d,
	0xa8, 0x37, 0x8f, 0x16, 0x0a, 0x22, 0x7b, 0xd9, 0x0a, 0x82, 0xb7, 0x35, 0x9d, 0x68, 0x59, 0x93,
	0xd4, 0x4c, 0xda, 0xbf, 0x5f, 0x3a, 0xc1, 0x27, 0x7b, 0xf0, 0x14, 0xbe, 0xcc, 0xfc, 0x66, 0x3e,
	0x06, 0x4e, 0xd7, 0xc1, 0x47, 0x5f, 0x32, 0x85, 0xed, 0x4a, 0x53, 0x21, 0x84, 0x7d, 0xa3, 0xed,
	0xc4, 0x01, 0x54, 0xc4, 0xdc, 0xbc, 0xd0, 0x7c, 0x56, 0x61, 0x0e, 0x03, 0xa3, 0xed, 0x83, 0x6f,
	0xc9, 0xa9, 0xde, 0x45, 0xef, 0xea, 0xa8, 0xfe, 0x62, 0x1c, 0xc1, 0x7e, 0x5c, 0xc5, 0x37, 0x52,
	0x99, 0x14, 0x12, 0xa0, 0x82, 0x43, 0x9b, 0xf2, 0xaa, 0x2f, 0xff, 0x9f, 0xb8, 0xeb, 0x67, 0xbf,
	0x71, 0x4b, 0xb5, 0x97, 0xfa, 0x05, 0x26, 0x37, 0x70, 0xb6, 0x20, 0xb7, 0xfc, 0xde, 0x59, 0xd3,
	0xfb, 0x86, 0x38, 0xe2, 0x25, 0xec, 0x7c, 0x64, 0xeb, 0xf1, 0xf4, 0xa4, 0x30, 0xda, 0x16, 0x3f,
	0x9a, 0xc4, 0xf5, 0x1e, 0xc6, 0x7f, 0xb3, 0xbc, 0xf6, 0x8e, 0xe9, 0x1f, 0x61, 0x1c, 0x42, 0xe6,
	0x5b, 0x71, 0x1f, 0xd4, 0x99, 0x6f, 0xa7, 0x8f, 0x00, 0xf3, 0x59, 0xb5, 0x48, 0x17, 0xc1, 0x3b,
	0x18, 0xfe, 0x1e, 0x8d, 0xb9, 0x4c, 0xe9, 0x74, 0xcd, 0xcf, 0x3b, 0x6b, 0xc9, 0xe5, 0x76, 0xfc,
	0x34, 0xd2, 0xa1, 0xe1, 0x57, 0x6e, 0xb6, 0x14, 0x4a, 0xa3, 0x6d, 0x29, 0xe7, 0x7e, 0x3e, 0x90,
	0xe7, 0xfa, 0x23, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x6c, 0x91, 0xca, 0x8c, 0x01, 0x00, 0x00,
}
