version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "3000:3000"
    networks:
      - network
    command: ["./app"]

networks:
  network:
    external: true
