// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageWS struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWS) Reset()         { *m = MessageWS{} }
func (m *MessageWS) String() string { return proto.CompactTextString(m) }
func (*MessageWS) ProtoMessage()    {}
func (*MessageWS) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *MessageWS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWS.Unmarshal(m, b)
}
func (m *MessageWS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWS.Marshal(b, m, deterministic)
}
func (m *MessageWS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWS.Merge(m, src)
}
func (m *MessageWS) XXX_Size() int {
	return xxx_messageInfo_MessageWS.Size(m)
}
func (m *MessageWS) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWS.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWS proto.InternalMessageInfo

func (m *MessageWS) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MessageWS) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SendMessageWSRequest struct {
	Ws                   *MessageWS `protobuf:"bytes,1,opt,name=ws,proto3" json:"ws,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendMessageWSRequest) Reset()         { *m = SendMessageWSRequest{} }
func (m *SendMessageWSRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageWSRequest) ProtoMessage()    {}
func (*SendMessageWSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *SendMessageWSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageWSRequest.Unmarshal(m, b)
}
func (m *SendMessageWSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageWSRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageWSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageWSRequest.Merge(m, src)
}
func (m *SendMessageWSRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageWSRequest.Size(m)
}
func (m *SendMessageWSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageWSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageWSRequest proto.InternalMessageInfo

func (m *SendMessageWSRequest) GetWs() *MessageWS {
	if m != nil {
		return m.Ws
	}
	return nil
}

type BaseResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type MessageFCM struct {
	FcmToken             string   `protobuf:"bytes,1,opt,name=fcmToken,proto3" json:"fcmToken,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Sound                string   `protobuf:"bytes,4,opt,name=sound,proto3" json:"sound,omitempty"`
	Channel              string   `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageFCM) Reset()         { *m = MessageFCM{} }
func (m *MessageFCM) String() string { return proto.CompactTextString(m) }
func (*MessageFCM) ProtoMessage()    {}
func (*MessageFCM) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *MessageFCM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageFCM.Unmarshal(m, b)
}
func (m *MessageFCM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageFCM.Marshal(b, m, deterministic)
}
func (m *MessageFCM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageFCM.Merge(m, src)
}
func (m *MessageFCM) XXX_Size() int {
	return xxx_messageInfo_MessageFCM.Size(m)
}
func (m *MessageFCM) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageFCM.DiscardUnknown(m)
}

var xxx_messageInfo_MessageFCM proto.InternalMessageInfo

func (m *MessageFCM) GetFcmToken() string {
	if m != nil {
		return m.FcmToken
	}
	return ""
}

func (m *MessageFCM) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MessageFCM) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MessageFCM) GetSound() string {
	if m != nil {
		return m.Sound
	}
	return ""
}

func (m *MessageFCM) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type SendMessageFCMRequest struct {
	Fcm                  *MessageFCM `protobuf:"bytes,1,opt,name=fcm,proto3" json:"fcm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendMessageFCMRequest) Reset()         { *m = SendMessageFCMRequest{} }
func (m *SendMessageFCMRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageFCMRequest) ProtoMessage()    {}
func (*SendMessageFCMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{4}
}

func (m *SendMessageFCMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageFCMRequest.Unmarshal(m, b)
}
func (m *SendMessageFCMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageFCMRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageFCMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageFCMRequest.Merge(m, src)
}
func (m *SendMessageFCMRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageFCMRequest.Size(m)
}
func (m *SendMessageFCMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageFCMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageFCMRequest proto.InternalMessageInfo

func (m *SendMessageFCMRequest) GetFcm() *MessageFCM {
	if m != nil {
		return m.Fcm
	}
	return nil
}

type SendMessageFCMResponse struct {
	Fcm                  *MessageFCM `protobuf:"bytes,1,opt,name=fcm,proto3" json:"fcm,omitempty"`
	Ok                   bool        `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendMessageFCMResponse) Reset()         { *m = SendMessageFCMResponse{} }
func (m *SendMessageFCMResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageFCMResponse) ProtoMessage()    {}
func (*SendMessageFCMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{5}
}

func (m *SendMessageFCMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageFCMResponse.Unmarshal(m, b)
}
func (m *SendMessageFCMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageFCMResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageFCMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageFCMResponse.Merge(m, src)
}
func (m *SendMessageFCMResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageFCMResponse.Size(m)
}
func (m *SendMessageFCMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageFCMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageFCMResponse proto.InternalMessageInfo

func (m *SendMessageFCMResponse) GetFcm() *MessageFCM {
	if m != nil {
		return m.Fcm
	}
	return nil
}

func (m *SendMessageFCMResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*MessageWS)(nil), "fcm.MessageWS")
	proto.RegisterType((*SendMessageWSRequest)(nil), "fcm.SendMessageWSRequest")
	proto.RegisterType((*BaseResponse)(nil), "fcm.BaseResponse")
	proto.RegisterType((*MessageFCM)(nil), "fcm.MessageFCM")
	proto.RegisterType((*SendMessageFCMRequest)(nil), "fcm.SendMessageFCMRequest")
	proto.RegisterType((*SendMessageFCMResponse)(nil), "fcm.SendMessageFCMResponse")
}

func init() {
	proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba)
}

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xd3, 0x45, 0x14, 0x46, 0x82, 0xba, 0x22, 0xa9, 0x35, 0x21, 0xda, 0x93, 0x17, 0x21,
	0xc1, 0xc4, 0x83, 0xf1, 0x04, 0x09, 0x89, 0x31, 0xbd, 0x14, 0x13, 0x13, 0x6f, 0x75, 0x99, 0x02,
	0x81, 0x76, 0xb1, 0x53, 0xe0, 0x15, 0x7c, 0x01, 0xdf, 0xd7, 0x74, 0xba, 0x45, 0x24, 0x24, 0x9e,
	0xda, 0x7f, 0xe7, 0xfb, 0xb7, 0xf3, 0xcf, 0x14, 0xce, 0x17, 0x89, 0x4e, 0x75, 0x87, 0x30, 0x59,
	0x4d, 0x15, 0xb6, 0x59, 0xc9, 0x52, 0xa8, 0x22, 0xf7, 0x0e, 0xaa, 0x1e, 0x12, 0x05, 0x63, 0x7c,
	0x1b, 0xca, 0x3a, 0x88, 0x54, 0xdb, 0xd6, 0xb5, 0x75, 0x5b, 0xf5, 0x45, 0xaa, 0xe5, 0x29, 0x94,
	0x22, 0x1a, 0xdb, 0x82, 0x0f, 0xb2, 0x57, 0xf7, 0x01, 0x1a, 0x43, 0x8c, 0x47, 0x1b, 0x8b, 0x8f,
	0x9f, 0x4b, 0xa4, 0x54, 0xb6, 0x40, 0xac, 0x89, 0x9d, 0xc7, 0xdd, 0x7a, 0x3b, 0x54, 0x51, 0xfb,
	0x17, 0x11, 0x6b, 0x72, 0x5b, 0x50, 0xeb, 0x05, 0x84, 0x3e, 0xd2, 0x42, 0xc7, 0x84, 0xd9, 0x97,
	0xf4, 0x8c, 0xf9, 0x8a, 0x2f, 0xf4, 0xcc, 0xfd, 0xb2, 0x00, 0x8c, 0x63, 0xd0, 0xf7, 0xa4, 0x03,
	0x95, 0x50, 0x45, 0xaf, 0x7a, 0x86, 0xb1, 0x69, 0x67, 0xa3, 0x65, 0x03, 0xca, 0xe9, 0x34, 0x9d,
	0xa3, 0x69, 0x2b, 0x17, 0xd2, 0x86, 0xa3, 0x28, 0xf7, 0xdb, 0x25, 0x3e, 0x2f, 0x64, 0xc6, 0x93,
	0x5e, 0xc6, 0x23, 0xfb, 0x20, 0xe7, 0x59, 0x64, 0xbc, 0x9a, 0x04, 0x71, 0x8c, 0x73, 0xbb, 0x9c,
	0xf3, 0x46, 0xba, 0x8f, 0x70, 0xb1, 0x15, 0x71, 0xd0, 0xf7, 0x8a, 0x8c, 0x37, 0x90, 0x4d, 0xcc,
	0x84, 0x3c, 0xd9, 0x0e, 0x99, 0x41, 0x3c, 0xcd, 0x17, 0x68, 0xee, 0x7a, 0x4d, 0xe0, 0xff, 0xcd,
	0x66, 0x26, 0xa2, 0x98, 0x49, 0xf7, 0xdb, 0x02, 0x18, 0xe6, 0x1b, 0xf3, 0x68, 0x2c, 0x9f, 0xa1,
	0xfe, 0xf7, 0x6e, 0xe9, 0xf0, 0x35, 0x7b, 0x9b, 0x75, 0xae, 0xf6, 0xd6, 0x4c, 0x33, 0x4f, 0x50,
	0x2b, 0x2a, 0xbc, 0xf7, 0xcb, 0x5d, 0x78, 0xb3, 0x58, 0xe7, 0x8c, 0x4b, 0xdb, 0xbb, 0xeb, 0x35,
	0xdf, 0x1b, 0x2a, 0x09, 0x68, 0x42, 0xc1, 0x0a, 0x93, 0x4e, 0xa8, 0xa2, 0x0e, 0xff, 0x4f, 0x1f,
	0x87, 0xfc, 0xb8, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x24, 0x30, 0x68, 0x6d, 0x02, 0x00,
	0x00,
}
