// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ServiceMsg_SendMessageFCM_FullMethodName = "/fcm.ServiceMsg/SendMessageFCM"
	ServiceMsg_SendMessgeWS_FullMethodName   = "/fcm.ServiceMsg/SendMessgeWS"
)

// ServiceMsgClient is the client API for ServiceMsg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceMsgClient interface {
	SendMessageFCM(ctx context.Context, in *SendMessageFCMRequest, opts ...grpc.CallOption) (*SendMessageFCMResponse, error)
	SendMessgeWS(ctx context.Context, in *SendMessageWSRequest, opts ...grpc.CallOption) (*BaseResponse, error)
}

type serviceMsgClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceMsgClient(cc grpc.ClientConnInterface) ServiceMsgClient {
	return &serviceMsgClient{cc}
}

func (c *serviceMsgClient) SendMessageFCM(ctx context.Context, in *SendMessageFCMRequest, opts ...grpc.CallOption) (*SendMessageFCMResponse, error) {
	out := new(SendMessageFCMResponse)
	err := c.cc.Invoke(ctx, ServiceMsg_SendMessageFCM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceMsgClient) SendMessgeWS(ctx context.Context, in *SendMessageWSRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, ServiceMsg_SendMessgeWS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceMsgServer is the server API for ServiceMsg service.
// All implementations must embed UnimplementedServiceMsgServer
// for forward compatibility
type ServiceMsgServer interface {
	SendMessageFCM(context.Context, *SendMessageFCMRequest) (*SendMessageFCMResponse, error)
	SendMessgeWS(context.Context, *SendMessageWSRequest) (*BaseResponse, error)
	mustEmbedUnimplementedServiceMsgServer()
}

// UnimplementedServiceMsgServer must be embedded to have forward compatible implementations.
type UnimplementedServiceMsgServer struct {
}

func (UnimplementedServiceMsgServer) SendMessageFCM(context.Context, *SendMessageFCMRequest) (*SendMessageFCMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageFCM not implemented")
}
func (UnimplementedServiceMsgServer) SendMessgeWS(context.Context, *SendMessageWSRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessgeWS not implemented")
}
func (UnimplementedServiceMsgServer) mustEmbedUnimplementedServiceMsgServer() {}

// UnsafeServiceMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceMsgServer will
// result in compilation errors.
type UnsafeServiceMsgServer interface {
	mustEmbedUnimplementedServiceMsgServer()
}

func RegisterServiceMsgServer(s grpc.ServiceRegistrar, srv ServiceMsgServer) {
	s.RegisterService(&ServiceMsg_ServiceDesc, srv)
}

func _ServiceMsg_SendMessageFCM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageFCMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceMsgServer).SendMessageFCM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceMsg_SendMessageFCM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceMsgServer).SendMessageFCM(ctx, req.(*SendMessageFCMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceMsg_SendMessgeWS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageWSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceMsgServer).SendMessgeWS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceMsg_SendMessgeWS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceMsgServer).SendMessgeWS(ctx, req.(*SendMessageWSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceMsg_ServiceDesc is the grpc.ServiceDesc for ServiceMsg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceMsg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fcm.ServiceMsg",
	HandlerType: (*ServiceMsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessageFCM",
			Handler:    _ServiceMsg_SendMessageFCM_Handler,
		},
		{
			MethodName: "SendMessgeWS",
			Handler:    _ServiceMsg_SendMessgeWS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
