// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Os                   string   `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	MsgError             string   `protobuf:"bytes,5,opt,name=msgError,proto3" json:"msgError,omitempty"`
	CodeError            int32    `protobuf:"varint,6,opt,name=codeError,proto3" json:"codeError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TokenResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *TokenResponse) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *TokenResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *TokenResponse) GetMsgError() string {
	if m != nil {
		return m.MsgError
	}
	return ""
}

func (m *TokenResponse) GetCodeError() int32 {
	if m != nil {
		return m.CodeError
	}
	return 0
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	DistanceRadius       int32    `protobuf:"varint,6,opt,name=distanceRadius,proto3" json:"distanceRadius,omitempty"`
	FcmToken             string   `protobuf:"bytes,7,opt,name=fcmToken,proto3" json:"fcmToken,omitempty"`
	StatusEN             string   `protobuf:"bytes,8,opt,name=statusEN,proto3" json:"statusEN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetDistanceRadius() int32 {
	if m != nil {
		return m.DistanceRadius
	}
	return 0
}

func (m *User) GetFcmToken() string {
	if m != nil {
		return m.FcmToken
	}
	return ""
}

func (m *User) GetStatusEN() string {
	if m != nil {
		return m.StatusEN
	}
	return ""
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{3}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{4}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenRequest)(nil), "fcm.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "fcm.TokenResponse")
	proto.RegisterType((*User)(nil), "fcm.User")
	proto.RegisterType((*GetUserRequest)(nil), "fcm.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "fcm.GetUserResponse")
}

func init() {
	proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144)
}

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0xae, 0xd3, 0x30,
	0x10, 0x56, 0xf2, 0xd2, 0xf6, 0x65, 0x0a, 0x05, 0xcc, 0x03, 0xa2, 0xea, 0x21, 0x55, 0x11, 0x42,
	0x5d, 0xb5, 0x55, 0xe1, 0x02, 0x20, 0x55, 0x88, 0x4d, 0x17, 0x29, 0xb0, 0x60, 0xe7, 0x26, 0x13,
	0x6a, 0x91, 0xc4, 0xc5, 0xe3, 0x54, 0xe2, 0x2c, 0x1c, 0x81, 0x3b, 0x71, 0x16, 0xe4, 0x9f, 0xf4,
	0x07, 0xa9, 0x12, 0x2b, 0xfb, 0xfb, 0x19, 0xfb, 0x1b, 0x7b, 0xe0, 0xf1, 0x5e, 0x49, 0x2d, 0xe7,
	0xbc, 0xd5, 0xbb, 0x99, 0xdd, 0xb2, 0x9b, 0x32, 0xaf, 0xd3, 0x57, 0xf0, 0xe0, 0x93, 0xfc, 0x8e,
	0x4d, 0x86, 0x3f, 0x5a, 0x24, 0xcd, 0xee, 0xa0, 0xa7, 0x0d, 0x4e, 0x82, 0x49, 0x30, 0x8d, 0x33,
	0x07, 0xd2, 0x5f, 0x01, 0x3c, 0xf4, 0x36, 0xda, 0xcb, 0x86, 0x90, 0x3d, 0x87, 0x7e, 0x4b, 0xa8,
	0x3e, 0x16, 0xde, 0xe8, 0x91, 0xa9, 0xc7, 0x9a, 0x8b, 0x2a, 0x09, 0x5d, 0xbd, 0x05, 0x6c, 0x04,
	0xa1, 0xa4, 0xe4, 0xc6, 0x52, 0xa1, 0x24, 0xc6, 0x20, 0x52, 0xb2, 0xc2, 0x24, 0xb2, 0x8c, 0xdd,
	0xb3, 0x31, 0xdc, 0xd6, 0xf4, 0x6d, 0xa5, 0x94, 0x54, 0x49, 0xcf, 0xf2, 0x47, 0xcc, 0xee, 0x21,
	0xce, 0x65, 0x81, 0x4e, 0xec, 0x4f, 0x82, 0x69, 0x2f, 0x3b, 0x11, 0xe9, 0x9f, 0x00, 0xa2, 0xcf,
	0x84, 0xca, 0x5c, 0x23, 0xba, 0x40, 0xa1, 0xb8, 0x16, 0xe6, 0x1e, 0xe2, 0x52, 0x28, 0xd2, 0x6b,
	0x5e, 0xa3, 0xcf, 0x74, 0x22, 0x4c, 0x8c, 0x8a, 0x7b, 0xd1, 0xc5, 0x3b, 0x62, 0xd3, 0x74, 0x2d,
	0xb7, 0xa2, 0x42, 0x1f, 0xd0, 0x23, 0xf6, 0x1a, 0x46, 0x85, 0x20, 0xcd, 0x9b, 0x1c, 0x33, 0x5e,
	0x88, 0x96, 0x7c, 0xc6, 0x7f, 0x58, 0x73, 0x76, 0x99, 0xd7, 0xf6, 0x21, 0x93, 0x81, 0x3b, 0xbb,
	0xc3, 0x46, 0x23, 0xcd, 0x75, 0x4b, 0xab, 0x75, 0x72, 0xeb, 0xb4, 0x0e, 0xa7, 0x53, 0x18, 0x7d,
	0x40, 0x6d, 0x5a, 0xec, 0xbe, 0xe9, 0xca, 0xf3, 0xa7, 0x0b, 0x78, 0x74, 0x74, 0xfa, 0x9f, 0x7a,
	0x09, 0x91, 0x11, 0xad, 0x71, 0xb8, 0x8c, 0x67, 0x65, 0x5e, 0xcf, 0xac, 0xc1, 0xd2, 0xcb, 0xdf,
	0x01, 0x0c, 0xdf, 0xb5, 0x7a, 0xb7, 0x41, 0x75, 0x10, 0x39, 0xb2, 0x05, 0x0c, 0x36, 0x48, 0x24,
	0x64, 0xc3, 0x9e, 0x58, 0xef, 0xf9, 0x78, 0x8c, 0xd9, 0x39, 0xe5, 0x2f, 0x78, 0x0b, 0xc3, 0x2f,
	0xa8, 0x44, 0xf9, 0xd3, 0x35, 0xf2, 0xdf, 0x55, 0x03, 0x9f, 0x94, 0x3d, 0xb5, 0xf2, 0x65, 0x87,
	0xe3, 0xbb, 0x4b, 0xd2, 0x55, 0xbd, 0x7f, 0xf1, 0xf5, 0x59, 0xae, 0x38, 0xed, 0x88, 0x1f, 0x50,
	0xd9, 0x61, 0x9e, 0xdb, 0x61, 0xde, 0xf6, 0xed, 0xf2, 0xe6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x0e, 0x68, 0x21, 0x6b, 0xe7, 0x02, 0x00, 0x00,
}
