// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAuth struct {
	Claims               *Claims  `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	ExpHours             uint32   `protobuf:"varint,2,opt,name=expHours,proto3" json:"expHours,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAuth) Reset()         { *m = CreateAuth{} }
func (m *CreateAuth) String() string { return proto.CompactTextString(m) }
func (*CreateAuth) ProtoMessage()    {}
func (*CreateAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *CreateAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuth.Unmarshal(m, b)
}
func (m *CreateAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuth.Marshal(b, m, deterministic)
}
func (m *CreateAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuth.Merge(m, src)
}
func (m *CreateAuth) XXX_Size() int {
	return xxx_messageInfo_CreateAuth.Size(m)
}
func (m *CreateAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuth.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuth proto.InternalMessageInfo

func (m *CreateAuth) GetClaims() *Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *CreateAuth) GetExpHours() uint32 {
	if m != nil {
		return m.ExpHours
	}
	return 0
}

type Claims struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RoleKey              string   `protobuf:"bytes,3,opt,name=roleKey,proto3" json:"roleKey,omitempty"`
	CompanyKey           string   `protobuf:"bytes,4,opt,name=companyKey,proto3" json:"companyKey,omitempty"`
	Os                   string   `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Claims) Reset()         { *m = Claims{} }
func (m *Claims) String() string { return proto.CompactTextString(m) }
func (*Claims) ProtoMessage()    {}
func (*Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claims.Unmarshal(m, b)
}
func (m *Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claims.Marshal(b, m, deterministic)
}
func (m *Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claims.Merge(m, src)
}
func (m *Claims) XXX_Size() int {
	return xxx_messageInfo_Claims.Size(m)
}
func (m *Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Claims proto.InternalMessageInfo

func (m *Claims) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Claims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Claims) GetRoleKey() string {
	if m != nil {
		return m.RoleKey
	}
	return ""
}

func (m *Claims) GetCompanyKey() string {
	if m != nil {
		return m.CompanyKey
	}
	return ""
}

func (m *Claims) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

type TokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	IgnoreSession        bool     `protobuf:"varint,2,opt,name=IgnoreSession,proto3" json:"IgnoreSession,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenRequest) GetIgnoreSession() bool {
	if m != nil {
		return m.IgnoreSession
	}
	return false
}

type SessionUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionUserRequest) Reset()         { *m = SessionUserRequest{} }
func (m *SessionUserRequest) String() string { return proto.CompactTextString(m) }
func (*SessionUserRequest) ProtoMessage()    {}
func (*SessionUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *SessionUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionUserRequest.Unmarshal(m, b)
}
func (m *SessionUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionUserRequest.Marshal(b, m, deterministic)
}
func (m *SessionUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionUserRequest.Merge(m, src)
}
func (m *SessionUserRequest) XXX_Size() int {
	return xxx_messageInfo_SessionUserRequest.Size(m)
}
func (m *SessionUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionUserRequest proto.InternalMessageInfo

func (m *SessionUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type TokenResponse struct {
	Token                string         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{4}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenResponse) GetError() *ErrorResponse {
	if m != nil {
		return m.Error
	}
	return nil
}

type VerifyTokenReponse struct {
	Claims               *Claims        `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	Error                *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VerifyTokenReponse) Reset()         { *m = VerifyTokenReponse{} }
func (m *VerifyTokenReponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenReponse) ProtoMessage()    {}
func (*VerifyTokenReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{5}
}

func (m *VerifyTokenReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenReponse.Unmarshal(m, b)
}
func (m *VerifyTokenReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenReponse.Marshal(b, m, deterministic)
}
func (m *VerifyTokenReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenReponse.Merge(m, src)
}
func (m *VerifyTokenReponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenReponse.Size(m)
}
func (m *VerifyTokenReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenReponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenReponse proto.InternalMessageInfo

func (m *VerifyTokenReponse) GetClaims() *Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *VerifyTokenReponse) GetError() *ErrorResponse {
	if m != nil {
		return m.Error
	}
	return nil
}

type SessionResponse struct {
	Claims               *Claims        `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	SessionId            string         `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Error                *ErrorResponse `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SessionResponse) Reset()         { *m = SessionResponse{} }
func (m *SessionResponse) String() string { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()    {}
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{6}
}

func (m *SessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponse.Unmarshal(m, b)
}
func (m *SessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponse.Marshal(b, m, deterministic)
}
func (m *SessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponse.Merge(m, src)
}
func (m *SessionResponse) XXX_Size() int {
	return xxx_messageInfo_SessionResponse.Size(m)
}
func (m *SessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponse proto.InternalMessageInfo

func (m *SessionResponse) GetClaims() *Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *SessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SessionResponse) GetError() *ErrorResponse {
	if m != nil {
		return m.Error
	}
	return nil
}

type ErrorResponse struct {
	MsgError             string   `protobuf:"bytes,1,opt,name=msgError,proto3" json:"msgError,omitempty"`
	CodeError            string   `protobuf:"bytes,2,opt,name=codeError,proto3" json:"codeError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{7}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetMsgError() string {
	if m != nil {
		return m.MsgError
	}
	return ""
}

func (m *ErrorResponse) GetCodeError() string {
	if m != nil {
		return m.CodeError
	}
	return ""
}

type ErrorAuth struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorAuth) Reset()         { *m = ErrorAuth{} }
func (m *ErrorAuth) String() string { return proto.CompactTextString(m) }
func (*ErrorAuth) ProtoMessage()    {}
func (*ErrorAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{8}
}

func (m *ErrorAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorAuth.Unmarshal(m, b)
}
func (m *ErrorAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorAuth.Marshal(b, m, deterministic)
}
func (m *ErrorAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorAuth.Merge(m, src)
}
func (m *ErrorAuth) XXX_Size() int {
	return xxx_messageInfo_ErrorAuth.Size(m)
}
func (m *ErrorAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorAuth.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorAuth proto.InternalMessageInfo

func (m *ErrorAuth) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorAuth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAuth)(nil), "auth.CreateAuth")
	proto.RegisterType((*Claims)(nil), "auth.Claims")
	proto.RegisterType((*TokenRequest)(nil), "auth.TokenRequest")
	proto.RegisterType((*SessionUserRequest)(nil), "auth.SessionUserRequest")
	proto.RegisterType((*TokenResponse)(nil), "auth.TokenResponse")
	proto.RegisterType((*VerifyTokenReponse)(nil), "auth.VerifyTokenReponse")
	proto.RegisterType((*SessionResponse)(nil), "auth.SessionResponse")
	proto.RegisterType((*ErrorResponse)(nil), "auth.ErrorResponse")
	proto.RegisterType((*ErrorAuth)(nil), "auth.ErrorAuth")
}

func init() {
	proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba)
}

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdf, 0x6f, 0xd3, 0x40,
	0x0c, 0x56, 0xfa, 0x8b, 0xc5, 0x6d, 0x36, 0x74, 0x63, 0x10, 0x55, 0x08, 0x4d, 0xd1, 0x1e, 0x86,
	0x84, 0x5a, 0xa9, 0x93, 0xd8, 0x04, 0xe2, 0x01, 0xca, 0x34, 0x0a, 0x12, 0x42, 0x19, 0xf0, 0xc0,
	0xdb, 0x91, 0x7a, 0x6b, 0x44, 0x92, 0x2b, 0x77, 0xc9, 0x44, 0xdf, 0xf6, 0xbf, 0xf2, 0x8f, 0xa0,
	0xf3, 0x5d, 0xd2, 0x45, 0xb4, 0x5a, 0xfb, 0x54, 0xfb, 0xb3, 0x3f, 0x7f, 0xf6, 0xd9, 0x29, 0xec,
	0xcf, 0xa5, 0xc8, 0xc5, 0x50, 0xa1, 0xbc, 0x89, 0x23, 0x1c, 0x90, 0xc7, 0x5a, 0xbc, 0xc8, 0x67,
	0xc1, 0x67, 0x80, 0xb1, 0x44, 0x9e, 0xe3, 0xdb, 0x22, 0x9f, 0xb1, 0x23, 0xe8, 0x44, 0x09, 0x8f,
	0x53, 0xe5, 0x3b, 0x87, 0xce, 0x71, 0x77, 0xd4, 0x1b, 0xe8, 0xa4, 0xc1, 0x98, 0xb0, 0xd0, 0xc6,
	0x58, 0x1f, 0x76, 0xf0, 0xcf, 0xfc, 0x83, 0x28, 0xa4, 0xf2, 0x1b, 0x87, 0xce, 0xb1, 0x17, 0x56,
	0x7e, 0x70, 0xeb, 0x40, 0xc7, 0xa4, 0xb3, 0xc7, 0xd0, 0x29, 0x14, 0xca, 0xc9, 0x94, 0x8a, 0xb9,
	0xa1, 0xf5, 0xd8, 0x23, 0x68, 0x63, 0xca, 0xe3, 0x84, 0xb8, 0x6e, 0x68, 0x1c, 0xe6, 0xc3, 0x03,
	0x29, 0x12, 0xfc, 0x84, 0x0b, 0xbf, 0x49, 0x78, 0xe9, 0xb2, 0x67, 0x00, 0x91, 0x48, 0xe7, 0x3c,
	0x5b, 0xe8, 0x60, 0x8b, 0x82, 0x77, 0x10, 0xb6, 0x0b, 0x0d, 0xa1, 0xfc, 0x36, 0xe1, 0x0d, 0xa1,
	0x82, 0x8f, 0xd0, 0xfb, 0x2a, 0x7e, 0x61, 0x16, 0xe2, 0xef, 0x02, 0x55, 0xae, 0xf5, 0x72, 0xed,
	0xdb, 0x36, 0x8c, 0xc3, 0x8e, 0xc0, 0x9b, 0x5c, 0x67, 0x42, 0xe2, 0x25, 0x2a, 0x15, 0x8b, 0x8c,
	0xba, 0xd9, 0x09, 0xeb, 0x60, 0xf0, 0x02, 0x98, 0x35, 0xbf, 0x29, 0x94, 0x65, 0xc5, 0x35, 0x93,
	0x05, 0x5f, 0xc0, 0xb3, 0xca, 0x6a, 0x2e, 0x32, 0x85, 0x6b, 0xa4, 0x9f, 0x43, 0x1b, 0xa5, 0x14,
	0x92, 0x24, 0xbb, 0xa3, 0x7d, 0xf3, 0xc8, 0xe7, 0x1a, 0x2a, 0x99, 0xa1, 0xc9, 0x08, 0x10, 0xd8,
	0x77, 0x94, 0xf1, 0xd5, 0xc2, 0xd6, 0x35, 0x65, 0x37, 0x5b, 0xd3, 0x16, 0x32, 0xb7, 0x0e, 0xec,
	0xd9, 0x39, 0xab, 0xde, 0x37, 0x13, 0x79, 0x0a, 0xae, 0x32, 0xc4, 0xc9, 0xd4, 0x2e, 0x74, 0x09,
	0x2c, 0x5b, 0x68, 0xde, 0xdb, 0xc2, 0x04, 0xbc, 0x1a, 0xae, 0xaf, 0x2c, 0x55, 0xd7, 0x84, 0xd9,
	0xe7, 0xab, 0x7c, 0xad, 0x1a, 0x89, 0x29, 0x9e, 0x57, 0xe3, 0xb9, 0xe1, 0x12, 0x08, 0x4e, 0xc0,
	0x25, 0x83, 0x4e, 0x9a, 0x41, 0x4b, 0x47, 0x6c, 0x09, 0xb2, 0x35, 0x96, 0xf1, 0x14, 0x2d, 0x93,
	0xec, 0xd1, 0xdf, 0x26, 0x74, 0x35, 0xe1, 0xd2, 0x7c, 0x24, 0xec, 0x25, 0x78, 0x17, 0x98, 0xa1,
	0xe4, 0x39, 0xd2, 0xdb, 0xb3, 0x87, 0x76, 0xfe, 0xea, 0x6b, 0xe9, 0xdb, 0x71, 0xea, 0x2b, 0x7f,
	0x0d, 0xdd, 0x3b, 0x1b, 0x63, 0xac, 0x96, 0x43, 0xe7, 0xd3, 0xf7, 0x0d, 0xb6, 0x62, 0xb1, 0x67,
	0xb0, 0x57, 0x8a, 0xda, 0x75, 0x6c, 0x2a, 0x7b, 0x0a, 0xbb, 0x21, 0x5e, 0x49, 0x54, 0xb3, 0x2d,
	0x89, 0x6f, 0x00, 0x2e, 0x30, 0x2f, 0x49, 0xb6, 0xb5, 0xff, 0x6f, 0xbe, 0x7f, 0x50, 0x8b, 0x54,
	0xf4, 0x57, 0xe0, 0x99, 0x39, 0xca, 0x0a, 0xab, 0x06, 0x5e, 0xc3, 0x3d, 0x03, 0xef, 0x3d, 0x26,
	0xb8, 0x9c, 0x75, 0x15, 0x77, 0xd5, 0xcd, 0xb0, 0x53, 0xe8, 0x8d, 0x13, 0xa1, 0xb6, 0x26, 0xbe,
	0x7b, 0xf2, 0xe3, 0x20, 0x92, 0x5c, 0xcd, 0x14, 0xbf, 0x41, 0x39, 0xd4, 0x09, 0x43, 0xfa, 0x37,
	0xfc, 0xd9, 0xa1, 0x9f, 0x93, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xee, 0x58, 0xf7, 0x56, 0x2b,
	0x05, 0x00, 0x00,
}
